# 
# 手動実行するworkflowのサンプル
# (step間の値の受け渡し、job間の値の受け渡し)
# 

# workflow の名前です。実行時に表示される
name: Manual workflow3

# on: アクションが実行されるタイミングを指定
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
      is-set-farewell-message:
        description: 'Set farewell message'
        required: false
        type: boolean

# job: この workflow で実行される処理を記載
jobs:
  greet:
    runs-on: ubuntu-latest

    # job 「greet」 の outputs を設定
    outputs:
      # ${{ needs.greet.outputs.farewell_message }} で値が参照できる
      farewell_message: ${{ steps.set-farewell-message.outputs.farewell-message }}

    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"

    - name: Prepare farewell message
      if: ${{ inputs.is-set-farewell-message }}
      # id: ステップのIDを設定
      id: set-farewell-message
      # 後の step で farewell_message を ${{ steps.set-farewell-message.outputs.farewell-message }} で参照できるようにする
      run: |
        echo "farewell-message=Did you receive the greeting I sent earlier?" >> "$GITHUB_OUTPUT"
        echo "----- debug ------------------------------"
        echo "\$GITHUB_OUTPUT: $GITHUB_OUTPUT"
        echo "cat \$GITHUB_OUTPUT"
        echo "======================="
        cat "$GITHUB_OUTPUT"
        echo "======================="
        echo "------------------------------------------"

    - name: Debug
      if: ${{ inputs.is-set-farewell-message }}
      # ${{ steps.set-farewell-message.outputs.farewell_message }} の値を表示
      # (stepのIDを指定して、"$GITHUB_OUTPUT"に設定された変数を取得)
      # ※それぞれの値の実態がわかるようにechoやcatを実行しています
      run: |
        echo "${{ steps.set-farewell-message.outputs.farewell-message }}"
        echo "----- debug ------------------------------"
        echo "\$GITHUB_OUTPUT: $GITHUB_OUTPUT"
        echo "cat \$GITHUB_OUTPUT"
        echo "======================="
        cat "$GITHUB_OUTPUT"
        echo "======================="
        echo "------------------------------------------"

  # 「farewell」という2つ目の job を用意
  farewell:
    # このジョブが実行される前に「greet」jobの完了が必要
    needs: greet

    runs-on: ubuntu-latest

    steps:
    - name: Send farewell if is-set-farewell-message flag is true
      if: ${{ inputs.is-set-farewell-message }}
      # greet で設定した output の値を参照
      run: echo "${{ needs.greet.outputs.farewell_message }}"

    - name: Send farewell
      run: echo "Goodbye ${{ inputs.name }}"
